// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function AddTodo(Props) {
  var label = Props.label;
  var id = Props.id;
  var value = Props.value;
  var onKeyPress = Props.onKeyPress;
  var onChange = Props.onChange;
  var tmp = {
    id: id,
    type: "text",
    value: value,
    onChange: onChange
  };
  if (onKeyPress !== undefined) {
    tmp.onKeyPress = Caml_option.valFromOption(onKeyPress);
  }
  return React.createElement(React.Fragment, undefined, React.createElement("label", {
                  htmlFor: id
                }, label), React.createElement("input", tmp));
}

var make = AddTodo;

export {
  make ,
  
}
/* react Not a pure module */
