// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function EmptyState$NoTodos(Props) {
  return React.createElement("div", {
              className: "bg-gray-100 p-8 mt-4 text-center text-sm text-gray-600 rounded"
            }, "You don't have any todos. Add one using the input above.");
}

var NoTodos = {
  make: EmptyState$NoTodos
};

function EmptyState$NoSearchResults(Props) {
  var query = Props.query;
  return React.createElement("div", {
              className: "bg-gray-100 p-8 mt-4 text-center text-sm text-gray-600 rounded"
            }, "There are no todos that match ", React.createElement("strong", undefined, query));
}

var NoSearchResults = {
  make: EmptyState$NoSearchResults
};

export {
  NoTodos ,
  NoSearchResults ,
  
}
/* react Not a pure module */
