// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function Input(Props) {
  var label = Props.label;
  var id = Props.id;
  var value = Props.value;
  var onKeyPress = Props.onKeyPress;
  var onChange = Props.onChange;
  var tmp = {
    className: "border-2 border-coolGray-300 py-2 px-4 rounded-sm w-full appearance-none bg-transparent dark:border-coolGray-600 focus:outline-none focus:ring-2 focus:ring-offset-4 dark:focus:ring-offset-coolGray-800 focus:ring-pink-300",
    id: id,
    type: "text",
    value: value,
    onChange: (function ($$event) {
        return Curry._1(onChange, $$event.target.value);
      })
  };
  if (onKeyPress !== undefined) {
    tmp.onKeyPress = Caml_option.valFromOption(onKeyPress);
  }
  return React.createElement(React.Fragment, undefined, React.createElement("label", {
                  className: "block text-sm font-bold text-gray-700 mb-2",
                  htmlFor: id
                }, label), React.createElement("input", tmp));
}

var make = Input;

export {
  make ,
  
}
/* react Not a pure module */
