// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Todo from "./Todo.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function TodoItem(Props) {
  var todo = Props.todo;
  var onToggle = Props.onToggle;
  var onRemove = Props.onRemove;
  var onUpdate = Props.onUpdate;
  var match = React.useState(function () {
        return Todo.content(todo);
      });
  var setTodoContent = match[1];
  var todoContent = match[0];
  var match$1 = React.useState(function () {
        return /* Idle */0;
      });
  var setTodoState = match$1[1];
  var tmp;
  if (match$1[0]) {
    tmp = React.createElement("label", undefined, React.createElement("span", {
              className: "sr-only"
            }, Todo.content(todo)), React.createElement("input", {
              type: "text",
              value: todoContent,
              onKeyPress: (function ($$event) {
                  if ($$event.key === "Enter") {
                    Curry._1(onUpdate, todoContent);
                    return Curry._1(setTodoState, (function (param) {
                                  return /* Idle */0;
                                }));
                  }
                  
                }),
              onChange: (function ($$event) {
                  var value = $$event.target.value;
                  return Curry._1(setTodoContent, (function (param) {
                                return value;
                              }));
                })
            }));
  } else {
    var tmp$1;
    tmp$1 = todo.TAG === /* Complete */0 ? " " + todo.completionDate.toISOString() : null;
    tmp = React.createElement("button", {
          onClick: (function (param) {
              return Curry._1(setTodoState, (function (param) {
                            return /* Updating */1;
                          }));
            })
        }, Todo.content(todo), tmp$1);
  }
  return React.createElement("li", {
              className: "flex items-center space-x-2"
            }, React.createElement("label", undefined, React.createElement("input", {
                      checked: Todo.isComplete(todo),
                      type: "checkbox",
                      onChange: onToggle
                    }), React.createElement("span", {
                      className: "sr-only"
                    }, Todo.content(todo))), tmp, React.createElement("button", {
                  onClick: onRemove
                }, "Remove todo"));
}

var make = TodoItem;

export {
  make ,
  
}
/* react Not a pure module */
