// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Icon from "./Icon.bs.js";
import * as Todo from "./Todo.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function TodoItem(Props) {
  var todo = Props.todo;
  var onToggle = Props.onToggle;
  var onRemove = Props.onRemove;
  var onUpdate = Props.onUpdate;
  var match = React.useState(function () {
        return Todo.content(todo);
      });
  var setTodoContent = match[1];
  var todoContent = match[0];
  var match$1 = React.useState(function () {
        return /* Idle */0;
      });
  var setTodoState = match$1[1];
  var tmp;
  if (match$1[0]) {
    tmp = React.createElement("label", {
          className: "flex-1"
        }, React.createElement("span", {
              className: "sr-only"
            }, Todo.content(todo)), React.createElement("textarea", {
              className: "w-full",
              autoFocus: true,
              type: "text",
              value: todoContent.trim(),
              onKeyPress: (function ($$event) {
                  var match = $$event.key;
                  var match$1 = todoContent.trim();
                  if (match !== "Enter") {
                    return ;
                  }
                  if (match$1 === "") {
                    return ;
                  }
                  Curry._1(onUpdate, match$1);
                  return Curry._1(setTodoState, (function (param) {
                                return /* Idle */0;
                              }));
                }),
              onChange: (function ($$event) {
                  var value = $$event.target.value;
                  return Curry._1(setTodoContent, (function (param) {
                                return value;
                              }));
                })
            }));
  } else {
    var tmp$1;
    tmp$1 = todo.TAG === /* Complete */0 ? React.createElement("span", {
            className: "text-xs text-gray-400 block mt-1"
          }, " " + todo.completionDate.toISOString()) : null;
    tmp = React.createElement("button", {
          className: "justify-between flex-1 text-left overflow-hidden text-sm py-1",
          onClick: (function (param) {
              return Curry._1(setTodoState, (function (param) {
                            return /* Updating */1;
                          }));
            })
        }, React.createElement("span", undefined, Todo.content(todo)), tmp$1);
  }
  return React.createElement("li", {
              className: "flex space-x-4 items-stretch bg-gray-100 border-gray-100 border pr-2 rounded"
            }, React.createElement("label", {
                  className: "bg-gray-200 flex items-center px-2"
                }, React.createElement("input", {
                      checked: Todo.isComplete(todo),
                      type: "checkbox",
                      onChange: onToggle
                    }), React.createElement("span", {
                      className: "sr-only"
                    }, Todo.content(todo))), tmp, React.createElement("button", {
                  className: "text-sm",
                  onClick: onRemove
                }, React.createElement(Icon.Remove.make, {}), React.createElement("span", {
                      className: "sr-only"
                    }, "Remove")));
}

var make = TodoItem;

export {
  make ,
  
}
/* Icon Not a pure module */
