// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Todo from "./Todo.bs.js";
import * as React from "react";

function TodoItem(Props) {
  var todo = Props.todo;
  var onToggle = Props.onToggle;
  var tmp;
  tmp = todo.TAG === /* Complete */0 ? todo.content + " " + todo.completionDate.toISOString() : todo.content;
  return React.createElement("li", undefined, React.createElement("label", {
                  className: "items-center flex space-x-2"
                }, React.createElement("input", {
                      checked: Todo.isComplete(todo),
                      type: "checkbox",
                      onChange: onToggle
                    }), React.createElement("div", undefined, tmp)));
}

var make = TodoItem;

export {
  make ,
  
}
/* react Not a pure module */
