// Generated by ReScript, PLEASE EDIT WITH CARE


function isComplete(todo) {
  if (todo.TAG === /* Complete */0) {
    return true;
  } else {
    return false;
  }
}

function toggle(todo) {
  if (todo.TAG === /* Complete */0) {
    return {
            TAG: /* Incomplete */1,
            content: todo.content
          };
  } else {
    return {
            TAG: /* Complete */0,
            content: todo.content,
            completionDate: new Date()
          };
  }
}

function content(todo) {
  return todo.content;
}

function updateContent(todo, updatedTodo) {
  if (todo.TAG === /* Complete */0) {
    return {
            TAG: /* Complete */0,
            content: updatedTodo,
            completionDate: todo.completionDate
          };
  } else {
    return {
            TAG: /* Incomplete */1,
            content: updatedTodo
          };
  }
}

export {
  isComplete ,
  toggle ,
  content ,
  updateContent ,
  
}
/* No side effect */
