// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Typography$H1(Props) {
  var children = Props.children;
  return React.createElement("h1", {
              className: "text-4xl font-bold mb-4"
            }, children);
}

var H1 = {
  make: Typography$H1
};

function Typography$H2(Props) {
  var children = Props.children;
  return React.createElement("h2", {
              className: "text-xl font-bold my-4 pb-1 border-b"
            }, children);
}

var H2 = {
  make: Typography$H2
};

export {
  H1 ,
  H2 ,
  
}
/* react Not a pure module */
